site_name: My Docs
nav:
    - Home: docs/README.md
    - Compiling and Running: docs/a_subdir/compiling_and_running.md
    - Creating A New Package: docs/a_subdir/creating_a_new_package.md

theme: readthedocs
