site_name: DUNE DAQ Software Documentation Home
nav:
    - Home: README.md
    - Packages:
       - appfwk: packages/appfwk/README.md
       - cmdlib: packages/cmdlib/README.md
       - daq-buildtools:
          - README: packages/daq-buildtools/README.md
          - Compiling-and-running: packages/daq-buildtools/Compiling-and-running.md
       - daq-cmake:
          - SchemaAndCodeGen: packages/daq-cmake/SchemaAndCodeGen.md
          - README: packages/daq-cmake/README.md
          - Creating-a-new-package-under-v2.3.0: packages/daq-cmake/Creating-a-new-package-under-v2.3.0.md
          - CmakeFunctions: packages/daq-cmake/CmakeFunctions.md
       - daqdemos: packages/daqdemos/README.md
       - dataformats: packages/dataformats/README.md
       - dfmessages: packages/dfmessages/README.md
       - dfmodules: packages/dfmodules/README.md
       - ers: packages/ers/README.md
       - ipm: packages/ipm/README.md
       - listrev: packages/listrev/README.md
       - logging: packages/logging/README.md
       - minidaqapp:
          - README: packages/minidaqapp/README.md
          - Reminders-about-tests-that-we-want-to-run: packages/minidaqapp/Reminders-about-tests-that-we-want-to-run.md
          - Coordination-notes-for-v2.3.0-and-v2.4.0: packages/minidaqapp/Coordination-notes-for-v2.3.0-and-v2.4.0.md
          - Notes-from-meetings-and-discussions: packages/minidaqapp/Notes-from-meetings-and-discussions.md
          - MiniDAQApp-Diagrams: packages/minidaqapp/MiniDAQApp-Diagrams.md
          - Simple-instructions-for-running-the-app: packages/minidaqapp/Simple-instructions-for-running-the-app.md
          - Instructions-for-setting-up-a-v2.4.0-development-environment: packages/minidaqapp/Instructions-for-setting-up-a-v2.4.0-development-environment.md
       - nwqueueadapters: packages/nwqueueadapters/README.md
       - opmonlib: packages/opmonlib/README.md
       - readout: packages/readout/README.md
       - restcmd: packages/restcmd/README.md
       - serialization: packages/serialization/README.md
       - trigemu: packages/trigemu/README.md

theme: mkdocs
