name: Simple Go Build
run-name: ${{ github.actor }} is running a simple Go program
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: golang:latest
    steps:
      - run: echo About to print the directory
      - run: pwd
      - run: echo About to list directory contents
      - run: ls
      - uses: actions/checkout@v3
      - name: Setup Go version
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.1'
      - run: go run hello-world.go
