name: JohnsJobWorkflow

on:
  push:
    branches:
      - main
      - master
jobs:
  johnsjob:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - var1: val1
            var2: val2
          - var1: val3
            var2: val4
          - var1: val5
            var2: val6

    steps:
    - name: Run Job
      run: echo "var1=${{ matrix.var1 }} var2=${{ matrix.var2 }}"
