
name: Simple Example of Uploading an Artifact
run-name: ${{ github.actor }} is uploading an artifact
on: 
  workflow_dispatch:

jobs:
  upload:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3
    - run: mkdir -p path/to/artifact
    - run: echo hello > path/to/artifact/world.txt
    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: path/to/artifact/world.txt

